version: '3'
services:
  api:
    image: 'node:12.18.4'
    working_dir: /server
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=app
      - PGPORT=5432
    depends_on: 
      - db
    volumes:
      - type: bind
        source: ./api
        target: /server
    command: bash -c "npm install && npm start"
  db:
    image: 'postgres:11.1'
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/setup/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
volumes:
  dbdata: